### ISSUE TITLE
可靠消息最终一致性的示例

### ISSUE THREAD

**Issue by ambluse** [HasonHuang/distributed-transaction-process#1]
请问可靠消息最终一致性的示例中如果遇到如下情况：

public AccountInfo createAccount(String name) {

    // db
    AccountInfo accountinfo = accountDao.create(name);

    // send message
   Result<Message> messageResult = 
   messageServiceClient.saveAndSendMessage(registerMessage(accountinfo));
                           
    // 这里出现了异常
    throw new RuntimeException("oh ... something wrong...");
}

如果在调用消息发送后一步出现异常，消息是否会发送到队列中去

**Comment by ambluse** [comment]
看了下 rm-message的逻辑，是不是在rm-message还是要含有业务逻辑的吗，需要通过rm-message来判断业务是否真正执行成功？

**Comment by HasonHuang** [comment]
@ambluse `rm-message`里有一个`消息状态确认子系统`，它的作用之一是在发生你说的情况时进行处理，它需要判断`createAccount`是否执行成功，若失败（如你说的抛出异常）则取消`createAccount`里要发送的消息，不对其进行发送。若成功则发送消息。

**Comment by ambluse** [comment]
了解 谢谢

**Comment by 852675742** [comment]
> @ambluse `rm-message`里有一个`消息状态确认子系统`，它的作用之一是在发生你说的情况时进行处理，它需要判断`createAccount`是否执行成功，若失败（如你说的抛出异常）则取消`createAccount`里要发送的消息，不对其进行发送。若成功则发送消息。

消息状态的只看到在定时器中处理啊
