### ISSUE TITLE
关于sping boot 和 tcc spring 版本的选择

### ISSUE THREAD

**Issue by DreamCartier** [HasonHuang/distributed-transaction-process#2]
我想问一下，关于spring boot里面的Spring jar 包和 tcc 框架里面的spring jar包，你是如何取舍的

**Comment by HasonHuang** [comment]
根据项目的需要决定哦，一般都是项目直接引用替换掉框架里的传递依赖，比如日志

**Comment by DreamCartier** [comment]
你好，您在spring boot 下面的配置domain和tbsuffix
@Bean
    public TransactionRepository transactionRepository(ObjectSerializer<?> serializer){
        SpringJdbcTransactionRepository repository = new SpringJdbcTransactionRepository();
        repository.setDataSource(tccDataSource());
        repository.setDomain("REDPACKET");
        repository.setTbSuffix("_REDPACKET");
        repository.setSerializer(serializer);
        return repository;
    }
请问这个和已经建立的数据表有什么关系吗

**Comment by HasonHuang** [comment]
这段代码是配置一个事务库，这个事务库的功能主要是查找未处理事务的日志和对日志增删改。
`domain`用于区分事务的种类，比如有红包、用户等事务。
`tbSuffix`就是事务表的后缀啦。

在`tcc-transaction`框架的`JdbcTransactionRepository`有下面一段代码：

```java
StringBuilder builder = new StringBuilder();
builder.append("SELECT GLOBAL_TX_ID, BRANCH_QUALIFIER, CONTENT,STATUS,TRANSACTION_TYPE,CREATE_TIME,LAST_UPDATE_TIME,RETRIED_COUNT,VERSION");
builder.append(StringUtils.isNotEmpty(domain) ? ",DOMAIN" : "");
builder.append("  FROM "+getTableName()+" WHERE LAST_UPDATE_TIME < ? AND TRANSACTION_TYPE = 1"); // TRANSACTION_TYPE=1（主事务:1）
builder.append(StringUtils.isNotEmpty(domain) ? " AND DOMAIN = ?" : "");
```

这段代码的作用是拼接一段SQL，用于查询某一种事务的未处理事务日志记录。
看完这段代码，你应该知道刚才的配置是用来干什么的啦~

**Comment by DreamCartier** [comment]
thanks,还有个问题，在主服务里面有段代码
LOG.debug("==try capitalTradeOrderService.record(null, buildCapitalTradeOrderDto(order) begin");
        // 资金帐户交易订单记录（因为此方法中有TransactionContext参数，因此也会被TccTransactionContextAspect拦截处理）
        String result = capitalTradeOrderService.record(null, buildCapitalTradeOrderDto(order));
这里主服务里面传递的是null???

**Comment by DreamCartier** [comment]
hi,可以加下QQ吗，2607679933，我们公司准备用这个生产环境，可以QQ聊下吗

**Comment by DreamCartier** [comment]
主服务调用从服务，从服务正常，但是主服务其他业务代码抛出异常了，从服务的事务不能回滚，从服务的cancel方法也没被调用！！！！这个是什么情况？？？！！！分布式事务的意义不就是这个吗，这个一致性保持不来，那么这个框架的意义是什么？？还是说的程序配置有问题？？

**Comment by DreamCartier** [comment]
主服务try阶段就已经控制事务回滚了，为什么还需要confirm和cancel？？？很是奇怪！！ @HasonHuang

**Comment by HasonHuang** [comment]
每个参与全局事务的try阶段，都属是参与事务，try阶段的失败回滚只是参与事务的回滚，其他参与事务并没有因此而回滚。所以需要cancel补偿
