### ISSUE TITLE
最终一致性的疑问？

### ISSUE THREAD

**Issue by 852675742** [HasonHuang/distributed-transaction-process#4]
请问下可靠消息最终一致性，发起方保存本地事件要在业务代码最后的位置嘛？另外消费者是单独的一个服务，还是放到具体的业务服务里面好呢，好比例子中积分消费服务？
![Uploading image.png…]()

**Comment by HasonHuang** [comment]
很久没更新项目，没有注意到你的问题，现在回答一下：
1、本地事务不需要在最后的位置，无论前后位置，都会有可能出问题；分2步调用消息服务正是为了解决这个问题。
2、都可以，各有优缺点。
